# Sử dụng Python 3.12 (có audioop)
FROM python:3.12-slim

# Đặt thư mục làm việc
WORKDIR /app

# Copy toàn bộ code vào container
COPY . .

# Cài thư viện cần thiết
RUN pip install -U pip
RUN pip install -r requirements.txt

# Chạy bot
CMD ["python", "main.py"]
